<?php
$scheduledTime = substr((string) array_get($record, 'scheduled_time'), 0, 5);
?>
<div class="row g-3">
    <div class="col-md-4"><label class="form-label fw-semibold">Parent</label><select class="form-select" name="parent_id" required><?php foreach ($parents as $parent): ?><option value="<?= (int) $parent['id'] ?>" <?= (int) array_get($record, 'parent_id', 0) === (int) $parent['id'] ? 'selected' : '' ?>><?= e(trim($parent['first_name'] . ' ' . $parent['last_name'])) ?></option><?php endforeach; ?></select></div>
    <div class="col-md-4"><label class="form-label fw-semibold">Student</label><select class="form-select" name="student_id" required><?php foreach ($students as $student): ?><option value="<?= (int) $student['id'] ?>" <?= (int) array_get($record, 'student_id', 0) === (int) $student['id'] ? 'selected' : '' ?>><?= e(trim($student['first_name'] . ' ' . $student['last_name'])) ?></option><?php endforeach; ?></select></div>
    <div class="col-md-4"><label class="form-label fw-semibold">Assigned rider</label><select class="form-select" name="assigned_driver_id"><option value="">Unassigned</option><?php foreach ($drivers as $driver): ?><option value="<?= (int) $driver['id'] ?>" <?= (int) array_get($record, 'assigned_driver_id', 0) === (int) $driver['id'] ? 'selected' : '' ?>><?= e(trim($driver['first_name'] . ' ' . $driver['last_name'])) ?></option><?php endforeach; ?></select></div>
    <div class="col-md-3"><label class="form-label fw-semibold">Scheduled date</label><input class="form-control" type="date" name="scheduled_date" value="<?= e(array_get($record, 'scheduled_date')) ?>" required></div>
    <div class="col-md-3"><label class="form-label fw-semibold">Scheduled time</label><input class="form-control" type="time" name="scheduled_time" value="<?= e($scheduledTime) ?>" required></div>
    <div class="col-md-3"><label class="form-label fw-semibold">Trip type</label><select class="form-select" name="trip_type"><?php foreach (array('one_way', 'round_trip', 'recurring') as $type): ?><option value="<?= e($type) ?>" <?= array_get($record, 'trip_type', 'one_way') === $type ? 'selected' : '' ?>><?= e(str_replace('_', ' ', ucfirst($type))) ?></option><?php endforeach; ?></select></div>
    <div class="col-md-3"><label class="form-label fw-semibold">Status</label><select class="form-select" name="booking_status"><?php foreach ($statuses as $status): ?><option value="<?= e($status) ?>" <?= array_get($record, 'booking_status', 'pending') === $status ? 'selected' : '' ?>><?= e(str_replace('_', ' ', ucfirst($status))) ?></option><?php endforeach; ?></select></div>
    <div class="col-md-6"><label class="form-label fw-semibold">Pickup address</label><textarea class="form-control" name="pickup_address" rows="2" required><?= e(array_get($record, 'pickup_address')) ?></textarea></div>
    <div class="col-md-6"><label class="form-label fw-semibold">Dropoff address</label><textarea class="form-control" name="dropoff_address" rows="2" required><?= e(array_get($record, 'dropoff_address')) ?></textarea></div>
    <div class="col-12"><label class="form-label fw-semibold">Notes</label><textarea class="form-control" name="notes" rows="2"><?= e(array_get($record, 'notes')) ?></textarea></div>
</div>
