<?php $recordId = array_get($record, 'id', 'new'); ?>
<div class="row g-3">
    <div class="col-md-6"><label class="form-label fw-semibold">Sender</label><select class="form-select" name="sender_user_id" required><?php foreach ($users as $user): ?><option value="<?= (int) $user['id'] ?>" <?= (int) array_get($record, 'sender_user_id', 0) === (int) $user['id'] ? 'selected' : '' ?>><?= e(trim($user['first_name'] . ' ' . $user['last_name'])) ?> - <?= e($user['email']) ?></option><?php endforeach; ?></select></div>
    <div class="col-md-6"><label class="form-label fw-semibold">Receiver</label><select class="form-select" name="receiver_user_id" required><?php foreach ($users as $user): ?><option value="<?= (int) $user['id'] ?>" <?= (int) array_get($record, 'receiver_user_id', 0) === (int) $user['id'] ? 'selected' : '' ?>><?= e(trim($user['first_name'] . ' ' . $user['last_name'])) ?> - <?= e($user['email']) ?></option><?php endforeach; ?></select></div>
    <div class="col-md-4"><label class="form-label fw-semibold">Ride</label><select class="form-select" name="ride_id"><option value="">None</option><?php foreach ($rides as $ride): ?><option value="<?= (int) $ride['id'] ?>" <?= (int) array_get($record, 'ride_id', 0) === (int) $ride['id'] ? 'selected' : '' ?>>Ride #<?= (int) $ride['id'] ?> - <?= e($ride['ride_status']) ?></option><?php endforeach; ?></select></div>
    <div class="col-md-4"><label class="form-label fw-semibold">Type</label><select class="form-select" name="message_type"><?php foreach (array('text', 'system', 'alert') as $type): ?><option value="<?= e($type) ?>" <?= array_get($record, 'message_type', 'text') === $type ? 'selected' : '' ?>><?= e(ucfirst($type)) ?></option><?php endforeach; ?></select></div>
    <div class="col-md-4 d-flex align-items-end"><div class="form-check"><input class="form-check-input" type="checkbox" name="is_read" value="1" id="mr<?= e($recordId) ?>" <?= !empty($record['is_read']) ? 'checked' : '' ?>><label class="form-check-label" for="mr<?= e($recordId) ?>">Read</label></div></div>
    <div class="col-12"><label class="form-label fw-semibold">Message</label><textarea class="form-control" name="message_text" rows="4" required><?= e(array_get($record, 'message_text')) ?></textarea></div>
</div>
