<div class="row g-3">
    <div class="col-md-4"><label class="form-label fw-semibold">First name</label><input class="form-control" name="first_name" value="<?= e($record['first_name'] ?? '') ?>" required></div>
    <div class="col-md-4"><label class="form-label fw-semibold">Middle name</label><input class="form-control" name="middle_name" value="<?= e($record['middle_name'] ?? '') ?>"></div>
    <div class="col-md-4"><label class="form-label fw-semibold">Last name</label><input class="form-control" name="last_name" value="<?= e($record['last_name'] ?? '') ?>" required></div>
    <div class="col-md-4"><label class="form-label fw-semibold">Email</label><input class="form-control" type="email" name="email" value="<?= e($record['email'] ?? '') ?>" required></div>
    <div class="col-md-4"><label class="form-label fw-semibold">Mobile</label><input class="form-control" name="mobile_number" value="<?= e($record['mobile_number'] ?? '') ?>" required></div>
    <div class="col-md-4"><label class="form-label fw-semibold">Password <?= !empty($record['id']) ? '<span class="text-secondary fw-normal">(optional)</span>' : '' ?></label><input class="form-control" type="password" name="password" <?= empty($record['id']) ? 'required' : '' ?>></div>
    <input type="hidden" name="role_code" value="student">
    <div class="col-md-4"><label class="form-label fw-semibold">Parent</label><select class="form-select" name="parent_id" required><?php foreach ($parents as $parent): ?><option value="<?= (int) $parent['id'] ?>" <?= (int) ($record['parent_id'] ?? 0) === (int) $parent['id'] ? 'selected' : '' ?>><?= e(trim($parent['first_name'] . ' ' . $parent['last_name'])) ?></option><?php endforeach; ?></select></div>
    <div class="col-md-4"><label class="form-label fw-semibold">User status</label><select class="form-select" name="user_status"><?php foreach (['pending', 'active', 'suspended', 'rejected'] as $status): ?><option value="<?= e($status) ?>" <?= ($record['user_status'] ?? 'active') === $status ? 'selected' : '' ?>><?= e(ucfirst($status)) ?></option><?php endforeach; ?></select></div>
    <div class="col-md-4"><label class="form-label fw-semibold">Student status</label><select class="form-select" name="student_status"><?php foreach (['active', 'inactive'] as $status): ?><option value="<?= e($status) ?>" <?= ($record['status'] ?? $record['student_status'] ?? 'active') === $status ? 'selected' : '' ?>><?= e(ucfirst($status)) ?></option><?php endforeach; ?></select></div>
    <div class="col-md-4"><label class="form-label fw-semibold">LRN</label><input class="form-control" name="lrn" value="<?= e($record['lrn'] ?? '') ?>" required></div>
    <div class="col-md-4"><label class="form-label fw-semibold">School</label><input class="form-control" name="school_name" value="<?= e($record['school_name'] ?? '') ?>" required></div>
    <div class="col-md-4"><label class="form-label fw-semibold">Grade level</label><input class="form-control" name="grade_level" value="<?= e($record['grade_level'] ?? '') ?>" required></div>
    <div class="col-md-6"><label class="form-label fw-semibold">Pickup address</label><textarea class="form-control" name="pickup_address" rows="2" required><?= e($record['pickup_address'] ?? '') ?></textarea></div>
    <div class="col-md-6"><label class="form-label fw-semibold">Dropoff address</label><textarea class="form-control" name="dropoff_address" rows="2" required><?= e($record['dropoff_address'] ?? '') ?></textarea></div>
    <div class="col-12"><label class="form-label fw-semibold">Medical notes</label><textarea class="form-control" name="medical_notes" rows="2"><?= e($record['medical_notes'] ?? '') ?></textarea></div>
    <div class="col-12"><div class="form-check"><input class="form-check-input" type="checkbox" name="is_verified" value="1" id="sv<?= e($record['id'] ?? 'new') ?>" <?= !empty($record['is_verified']) ? 'checked' : '' ?>><label class="form-check-label" for="sv<?= e($record['id'] ?? 'new') ?>">Verified account</label></div></div>
</div>

